# Generated by Django 3.1.6 on 2021-02-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20210217_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='country',
        ),
        migrations.AddField(
            model_name='company',
            name='cm1',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='cm2',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='cm3',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
